// Code generated by MockGen. DO NOT EDIT.
// Source: controller/word.go

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWordController is a mock of WordController interface.
type MockWordController struct {
	ctrl     *gomock.Controller
	recorder *MockWordControllerMockRecorder
}

// MockWordControllerMockRecorder is the mock recorder for MockWordController.
type MockWordControllerMockRecorder struct {
	mock *MockWordController
}

// NewMockWordController creates a new mock instance.
func NewMockWordController(ctrl *gomock.Controller) *MockWordController {
	mock := &MockWordController{ctrl: ctrl}
	mock.recorder = &MockWordControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWordController) EXPECT() *MockWordControllerMockRecorder {
	return m.recorder
}

// AddWord mocks base method.
func (m *MockWordController) AddWord(httpResponse http.ResponseWriter, httpRequest *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWord", httpResponse, httpRequest)
}

// AddWord indicates an expected call of AddWord.
func (mr *MockWordControllerMockRecorder) AddWord(httpResponse, httpRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWord", reflect.TypeOf((*MockWordController)(nil).AddWord), httpResponse, httpRequest)
}

// ListWords mocks base method.
func (m *MockWordController) ListWords(httpResponse http.ResponseWriter, httpRequest *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListWords", httpResponse, httpRequest)
}

// ListWords indicates an expected call of ListWords.
func (mr *MockWordControllerMockRecorder) ListWords(httpResponse, httpRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWords", reflect.TypeOf((*MockWordController)(nil).ListWords), httpResponse, httpRequest)
}
