// Code generated by MockGen. DO NOT EDIT.
// Source: controller/controller.go

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// AddWord mocks base method.
func (m *MockController) AddWord(httpResponse http.ResponseWriter, httpRequest *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWord", httpResponse, httpRequest)
}

// AddWord indicates an expected call of AddWord.
func (mr *MockControllerMockRecorder) AddWord(httpResponse, httpRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWord", reflect.TypeOf((*MockController)(nil).AddWord), httpResponse, httpRequest)
}

// CreateDictionary mocks base method.
func (m *MockController) CreateDictionary(httpResponse http.ResponseWriter, httpRequest *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateDictionary", httpResponse, httpRequest)
}

// CreateDictionary indicates an expected call of CreateDictionary.
func (mr *MockControllerMockRecorder) CreateDictionary(httpResponse, httpRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDictionary", reflect.TypeOf((*MockController)(nil).CreateDictionary), httpResponse, httpRequest)
}

// ListWords mocks base method.
func (m *MockController) ListWords(httpResponse http.ResponseWriter, httpRequest *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListWords", httpResponse, httpRequest)
}

// ListWords indicates an expected call of ListWords.
func (mr *MockControllerMockRecorder) ListWords(httpResponse, httpRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWords", reflect.TypeOf((*MockController)(nil).ListWords), httpResponse, httpRequest)
}
